import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Footer";
import dynamic from "next/dynamic";
import Navigation from "../components/Navigation";

const manrope = Manrope({ subsets: ["latin"] });
//const Navigation = dynamic(() => import("../components/Navigation"), {
// ssr: false,
// });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Navigation />
        {children}
        <Footer />
      </body>
    </html>
  );
}
